### ISSUE TITLE
Format Subpage | Template Buttons

### ISSUE THREAD

**Issue by kdavisva** [compensationServiceTraining/curriculumCreationGuide#13]
GM Per the template, all the buttons (back, pause, play, cc and next) are a combined button – the button and two smartshapes. All the buttons have the pause on them after 1.5 seconds. In many of our modules, we have bullets come in one at a time based on the audio. This causes the designer to have to remove the “pause after” for each button. Is it possible to make these buttons a single button? In addition, the buttons are quite large. Is it possible to reduce the size of the buttons? ((This is also a test to see if I am using the system correctly)

**Comment by artlessdodger** [comment]
Closed via implementation of v2.314 of the Captivate template. See commit [43b4b3f](https://github.com/compensationServiceTraining/curriculumCreationGuide/commit/43b4b3f98ae62f181f678dbbc59f152f22cc511a) and the [v2.215 release notes](https://github.com/compensationServiceTraining/curriculumCreationGuide/releases/tag/v2.215).
