### ISSUE TITLE
Format Subpage | Email Button Size/Positioning in the Template

### ISSUE THREAD

**Issue by cassbg** [compensationServiceTraining/curriculumCreationGuide#19]
Captivate Template suggestions: 
1. The email button (top-right corner of slide) may look nicer if made slightly smaller in size to match the size of other buttons on the slide (the CC button, for example).
2. The email button (top-right corner of slide) should be better aligned with the right arrow button that is positioned on the bottom-right corner of the slide. I believe the right side of the email button should match up with the right side of the right arrow button. 

Thanks!

**Comment by artlessdodger** [comment]
The email button has been removed [via unanimous consent of the Board](https://github.com/orgs/compensationServiceTraining/teams/ccg-change-control-board/discussions/12). See commit [43b4b3f](https://github.com/compensationServiceTraining/curriculumCreationGuide/commit/43b4b3f98ae62f181f678dbbc59f152f22cc511a).

![image](https://user-images.githubusercontent.com/51389101/134734876-0abf4eb5-9193-41a8-96a4-6da46636d183.png)
