### ISSUE TITLE
Captivate Template — Shape of Closed Captioning (CC) button 

### ISSUE THREAD

**Issue by cassbg** [compensationServiceTraining/curriculumCreationGuide#20]
Creating separate issue for @kdavisva's idea that was initially noted in the comments from our discussion about Issue 13. 

Can the CC button in the Captivate template be changed to match the format of the other buttons? The CC button is currently rectangular, whereas the other navigation buttons are rounded (next, back, pause, play, etc.). For consistency, please change the CC button to be round.

If you agree with changing the CC button to be rounded (to match the style used for other navigation buttons in the template), please give us a thumbs up reaction to this post. 

Thank you!

**Comment by artlessdodger** [comment]
Closed via implementation of v2.314 of the Captivate template. See commit [43b4b3f](https://github.com/compensationServiceTraining/curriculumCreationGuide/commit/43b4b3f98ae62f181f678dbbc59f152f22cc511a) and the [v2.215 release notes](https://github.com/compensationServiceTraining/curriculumCreationGuide/releases/tag/v2.215).
