### ISSUE TITLE
Format Subpage | Published Files Folder

### ISSUE THREAD

**Issue by DevinJohnston** [compensationServiceTraining/curriculumCreationGuide#24]
The question came up today as to who is responsible for adding the published file to the cptx file, the author or the publisher? If it is the publisher, I suggest adding steps showing adding the published files to the cptx repository and potentially linking to the CCG formatting section that shows the file layout. If it is the author and that is stated somewhere in the CCG- sorry, I missed it! If the author, maybe we can add this detail to the Creating and Updating Curriculum Items steps?

**Comment by artlessdodger** [comment]
Implemented [via unanimous consent of the Board](https://github.com/orgs/compensationServiceTraining/teams/ccg-change-control-board/discussions/14). See commit [b450a56](https://github.com/compensationServiceTraining/curriculumCreationGuide/commit/b450a56457bc8cfedbea294917f2834e0eaac22c).

![image](https://user-images.githubusercontent.com/51389101/134736942-db994608-3cfc-445c-ab29-949de6291cb2.png)
