### ISSUE TITLE
Format Subpage | Folder Hierarchy | Connect

### ISSUE THREAD

**Issue by DevinJohnston** [compensationServiceTraining/curriculumCreationGuide#25]
Please add brief summary of the purpose of the Connect folder and its contents. Something like:

The Course Project Folder in Connect is used for peer review, concurrence, and publication and should contain all published content for each course. Each folder should include historical course materials, linked media (for example, PDFs that are linked to open from within the published course), copies of all feedback and responses for concurrence and peer review, and the final Published file(s), Slide Notes, Transcripts, Answer Keys, Change Form, and IRF. See folders | connect for naming conventions.

Please change name of Media folder to Linked Media

**Comment by cassbg** [comment]
Implemented in v2.216 release dated 11292021.
