### ISSUE TITLE
Change subpage | 213A membership

### ISSUE THREAD

**Issue by cassbg** [compensationServiceTraining/curriculumCreationGuide#28]
In the CCG, the Change Control Board membership list on the Change page needs to be updated to reflect that the current member for 213A Certification Staff is now Dee Dee Reeves.

**Comment by artlessdodger** [comment]
This was changed in commit [43b4b3f](https://github.com/compensationServiceTraining/curriculumCreationGuide/commit/43b4b3f98ae62f181f678dbbc59f152f22cc511a), it just hasn't been published to Connect yet.
