### ISSUE TITLE
Create subpage | Provide link to CPTX file for peer/editorial review

### ISSUE THREAD

**Issue by aricdostal** [compensationServiceTraining/curriculumCreationGuide#35]
I'd like to suggest providing access to CPTX files along with the slide notes pages and links to the presentation for internal reviewers. I find it much easier to identify style errors related to spacing, fonts, margins, alignment, etc. if I can review the content in the CPTX working file. It would also make it possible to identify and/or address issues in functionality related to variables and advance actions as the review is being conducted.

Thank you,
Aric

**Comment by cassbg** [comment]
Implemented in v2.216 release dated 11292021.
