### ISSUE TITLE
Create Subpage | Revision to Connect Project Folder Organization

### ISSUE THREAD

**Issue by jrgranger** [compensationServiceTraining/curriculumCreationGuide#48]
213F Leadership would like revision to the Course Project folder organization in Connect. Specifically, they want to discontinue the use of alternative parent folders, such as **Course Project Folders | Peer Review**, in Connect and moving course material folders that are currently undergoing development/review.

Ideally, course folders should stay where they are regardless of development/update review status. For example, active course folders for VSR Predetermination VIP curriculum content should always remain in the **VSR | Predetermination Courses** parent folder and never be moved, unless the course has been decommissioned and archived (i.e. moved to the **Archived Courses** folder).

The main reason for this suggestion is that utilizing alternative parent folder locations interferes with the business needs of our virtual studio support contractors to easily locate studio content to upload into our virtual studios, as they may not have any awareness as to whether a course is being updated or not or which alternative folder a course folder might be located in. This causes unnecessary confusion and customer service inquiries on our own staff members to try to locate these materials for them, etc.

Additionally, with the creation of subfolders within the actual course content folders specifically for peer review, concurrence and editorial documentation, having extraneous parent folder locations seems duplicative and unnecessary, adding additional tasks and lending additional room for human error.

Personally, I think eliminating these extra folder locations will help simplify and improve the overall organization and navigability of the shared content folder in Connect in general. 

If anyone has anything to contribute to this issue one way or another, please comment below. Please defer this matter for discussion at our next meeting.

**Comment by artlessdodger** [comment]
Agreed on my end — the initial Course Project Folder | X locations were created when we did not have a better solution. Project tracking in GitHub using the courseUpdates repository project is significantly simpler.

**Comment by lukebelcher** [comment]
Closing this issue out since it coincides with issue 42.  Added the comments from this issue to issue 42 as well. 

URL to issue 42 - [https://github.com/compensationServiceTraining/curriculumCreationGuide/issues/42](url)
